### ISSUE TITLE
Opencv-4.2.0

### ISSUE THREAD

**Issue by InduGirish** [MrLacuqer/hj-object-detect#4]
Does it work with opencv-4.2.0, ros-melodic in ubuntu-18.04

**Comment by hj26-park** [comment]
I’m not sure about the OpenCV version, but it will working.
Yes! melodic also working.
Now I’m using in Melodic.

**Comment by InduGirish** [comment]
I got the following error when  I build darknet_ros, with opencv-4.2.0, cuda-10.1

Error
-------
In file included from /usr/local/include/opencv4/opencv2/core/types_c.h:84:0,
                 from /usr/local/include/opencv4/opencv2/core/core_c.h:48,
                 from /usr/local/include/opencv4/opencv2/highgui/highgui_c.h:45,
                 from /home/girishkumar/catkin_ws/src/darknet_ros/darknet/include/darknet.h:25,
                 from /home/girishkumar/catkin_ws/src/darknet_ros/darknet/src/activations.h:3,
                 from /home/girishkumar/catkin_ws/src/darknet_ros/darknet/src/activations.c:1:
/usr/local/include/opencv4/opencv2/core/cvdef.h:704:4: error: #error "OpenCV 4.x+ requires enabled C++11 support"
 #  error "OpenCV 4.x+ requires enabled C++11 support"
    ^~~~~
compilation terminated due to -Wfatal-errors.
In file included from /usr/local/include/opencv4/opencv2/core/types_c.h:84:0,
                 from /usr/local/include/opencv4/opencv2/core/core_c.h:48,
                 from /usr/local/include/opencv4/opencv2/highgui/highgui_c.h:45,
                 from /home/girishkumar/catkin_ws/src/darknet_ros/darknet/include/darknet.h:25,
                 from /home/girishkumar/catkin_ws/src/darknet_ros/darknet/src/box.h:3,
                 from /home/girishkumar/catkin_ws/src/darknet_ros/darknet/src/image.h:9,
                 from /home/girishkumar/catkin_ws/src/darknet_ros/darknet/src/image.c:1:
/usr/local/include/opencv4/opencv2/core/cvdef.h:704:4: error: #error "OpenCV 4.x+ requires enabled C++11 support"
 #  error "OpenCV 4.x+ requires enabled C++11 support"
    ^~~~~
compilation terminated due to -Wfatal-errors.
In file included from /usr/local/include/opencv4/opencv2/core/types_c.h:84:0,
                 from /usr/local/include/opencv4/opencv2/core/core_c.h:48,
                 from /usr/local/include/opencv4/opencv2/highgui/highgui_c.h:45,
                 from /home/girishkumar/catkin_ws/src/darknet_ros/darknet/include/darknet.h:25,
                 from /home/girishkumar/catkin_ws/src/darknet_ros/darknet/src/box.h:3,
                 from /home/girishkumar/catkin_ws/src/darknet_ros/darknet/src/image.h:9,
                 from /home/girishkumar/catkin_ws/src/darknet_ros/darknet_ros/include/darknet_ros/image_interface.h:12,
                 from /home/girishkumar/catkin_ws/src/darknet_ros/darknet_ros/src/image_interface.c:9:
/usr/local/include/opencv4/opencv2/core/cvdef.h:704:4: error: #error "OpenCV 4.x+ requires enabled C++11 support"
 #  error "OpenCV 4.x+ requires enabled C++11 support"
    ^~~~~
compilation terminated due to -Wfatal-errors.
In file included from /usr/local/include/opencv4/opencv2/core/types_c.h:84:0,
                 from /usr/local/include/opencv4/opencv2/core/core_c.h:48,
                 from /usr/local/include/opencv4/opencv2/highgui/highgui_c.h:45,
                 from /home/girishkumar/catkin_ws/src/darknet_ros/darknet/include/darknet.h:25,
                 from /home/girishkumar/catkin_ws/src/darknet_ros/darknet/src/box.h:3,
                 from /home/girishkumar/catkin_ws/src/darknet_ros/darknet/src/image.h:9,
                 from /home/girishkumar/catkin_ws/src/darknet_ros/darknet/src/avgpool_layer.h:4,
                 from /home/girishkumar/catkin_ws/src/darknet_ros/darknet/src/avgpool_layer.c:1:
/usr/local/include/opencv4/opencv2/core/cvdef.h:704:4: error: #error "OpenCV 4.x+ requires enabled C++11 support"
 #  error "OpenCV 4.x+ requires enabled C++11 support"
    ^~~~~
In file included from /usr/local/include/opencv4/opencv2/core/types_c.h:84:0,
                 from /usr/local/include/opencv4/opencv2/core/core_c.h:48,
                 from /usr/local/include/opencv4/opencv2/highgui/highgui_c.h:45,
                 from /home/girishkumar/catkin_ws/src/darknet_ros/darknet/include/darknet.h:25,
                 from /home/girishkumar/catkin_ws/src/darknet_ros/darknet/src/layer.h:1,
                 from /home/girishkumar/catkin_ws/src/darknet_ros/darknet/src/layer.c:1:
/usr/local/include/opencv4/opencv2/core/cvdef.h:704:4: error: #error "OpenCV 4.x+ requires enabled C++11 support"
 #  error "OpenCV 4.x+ requires enabled C++11 support"
    ^~~~~
compilation terminated due to -Wfatal-errors.
compilation terminated due to -Wfatal-errors.
darknet_ros/darknet_ros/CMakeFiles/darknet_ros_lib.dir/build.make:2052: recipe for target 'darknet_ros/darknet_ros/CMakeFiles/darknet_ros_lib.dir/__/darknet/src/activations.c.o' failed
make[3]: *** [darknet_ros/darknet_ros/CMakeFiles/darknet_ros_lib.dir/__/darknet/src/activations.c.o] Error 1
make[3]: *** Waiting for unfinished jobs....
darknet_ros/darknet_ros/CMakeFiles/darknet_ros_lib.dir/build.make:2076: recipe for target 'darknet_ros/darknet_ros/CMakeFiles/darknet_ros_lib.dir/__/darknet/src/image.c.o' failed
make[3]: *** [darknet_ros/darknet_ros/CMakeFiles/darknet_ros_lib.dir/__/darknet/src/image.c.o] Error 1
darknet_ros/darknet_ros/CMakeFiles/darknet_ros_lib.dir/build.make:2100: recipe for target 'darknet_ros/darknet_ros/CMakeFiles/darknet_ros_lib.dir/__/darknet/src/avgpool_layer.c.o' failed
make[3]: *** [darknet_ros/darknet_ros/CMakeFiles/darknet_ros_lib.dir/__/darknet/src/avgpool_layer.c.o] Error 1
darknet_ros/darknet_ros/CMakeFiles/darknet_ros_lib.dir/build.make:2124: recipe for target 'darknet_ros/darknet_ros/CMakeFiles/darknet_ros_lib.dir/__/darknet/src/layer.c.o' failed
make[3]: *** [darknet_ros/darknet_ros/CMakeFiles/darknet_ros_lib.dir/__/darknet/src/layer.c.o] Error 1
darknet_ros/darknet_ros/CMakeFiles/darknet_ros_lib.dir/build.make:1980: recipe for target 'darknet_ros/darknet_ros/CMakeFiles/darknet_ros_lib.dir/src/image_interface.c.o' failed
make[3]: *** [darknet_ros/darknet_ros/CMakeFiles/darknet_ros_lib.dir/src/image_interface.c.o] Error 1
In file included from /usr/local/include/opencv4/opencv2/core/types_c.h:84:0,
                 from /usr/local/include/opencv4/opencv2/core/core_c.h:48,
                 from /usr/local/include/opencv4/opencv2/highgui/highgui_c.h:45,
                 from /home/girishkumar/catkin_ws/src/darknet_ros/darknet/include/darknet.h:25,
                 from /home/girishkumar/catkin_ws/src/darknet_ros/darknet/src/cuda.h:4,
                 from /home/girishkumar/catkin_ws/src/darknet_ros/darknet/src/convolutional_layer.h:4,
                 from /home/girishkumar/catkin_ws/src/darknet_ros/darknet/src/batchnorm_layer.c:1:
/usr/local/include/opencv4/opencv2/core/cvdef.h:704:4: error: #error "OpenCV 4.x+ requires enabled C++11 support"
 #  error "OpenCV 4.x+ requires enabled C++11 support"
    ^~~~~
compilation terminated due to -Wfatal-errors.

**Comment by hj26-park** [comment]
I'm sorry but, could you open to the [darknet_ros](https://github.com/leggedrobotics/darknet_ros) repository?
I can't help you.
